# Server
 server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/creditbuilder
spring.datasource.username=cbuser
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# App name
spring.application.name=credit-builder-api

#JWT
app.jwt.secret=creditbuilder-super-secret-key-change-in-production
app.jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
